package com.com3g.myPm.domaine;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Abscence generated by hbm2java
 */
@Entity
@Table(name = "abscence", catalog = "mypm")
public class Abscence implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private String ressourceId;
    private Date startDay;
    private Date endDay;
    private int nbDays;
    private String justified;
    private String type;
    private String payed;

    public Abscence() {
    }

    public Abscence(String ressourceId, Date startDay, Date endDay, int nbDays, String justified, String type,
	    String payed) {
	this.ressourceId = ressourceId;
	this.startDay = startDay;
	this.endDay = endDay;
	this.nbDays = nbDays;
	this.justified = justified;
	this.type = type;
	this.payed = payed;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    @Column(name = "ressource_id", nullable = false, length = 500)
    public String getRessourceId() {
	return this.ressourceId;
    }

    public void setRessourceId(String ressourceId) {
	this.ressourceId = ressourceId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "start_day", nullable = false, length = 10)
    public Date getStartDay() {
	return this.startDay;
    }

    public void setStartDay(Date startDay) {
	this.startDay = startDay;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "end_day", nullable = false, length = 10)
    public Date getEndDay() {
	return this.endDay;
    }

    public void setEndDay(Date endDay) {
	this.endDay = endDay;
    }

    @Column(name = "nb_days", nullable = false)
    public int getNbDays() {
	return this.nbDays;
    }

    public void setNbDays(int nbDays) {
	this.nbDays = nbDays;
    }

    @Column(name = "justified", nullable = false, length = 50)
    public String getJustified() {
	return this.justified;
    }

    public void setJustified(String justified) {
	this.justified = justified;
    }

    @Column(name = "type", nullable = false, length = 500)
    public String getType() {
	return this.type;
    }

    public void setType(String type) {
	this.type = type;
    }

    @Column(name = "payed", nullable = false, length = 50)
    public String getPayed() {
	return this.payed;
    }

    public void setPayed(String payed) {
	this.payed = payed;
    }

}
