package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Acceptance generated by hbm2java
 */
@Entity
@Table(name="acceptance"
    ,catalog="mypm"
)
public class Acceptance  implements java.io.Serializable {


     private Integer idacceptance;
     private Paymentterm paymentterm;
     private Date dateAcceptance;
     private String numero;
     private String linkGed;
     private String status;
     private Date dateInvoice;
     private String idInvoice;
     private String typeInvoice;
     private String type;
     private String invoiceStatus;
     private Date duedateInvoice;
     private Double vat;
     private Set<Acceptancedetails> acceptancedetailses = new HashSet<Acceptancedetails>(0);
     private Set<Payment> payments = new HashSet<Payment>(0);

    public Acceptance() {
    }

	
    public Acceptance(Paymentterm paymentterm) {
        this.paymentterm = paymentterm;
    }
    public Acceptance(Paymentterm paymentterm, Date dateAcceptance, String numero, String linkGed, String status, Date dateInvoice, String idInvoice, String typeInvoice, String type, String invoiceStatus, Date duedateInvoice, Double vat, Set<Acceptancedetails> acceptancedetailses, Set<Payment> payments) {
       this.paymentterm = paymentterm;
       this.dateAcceptance = dateAcceptance;
       this.numero = numero;
       this.linkGed = linkGed;
       this.status = status;
       this.dateInvoice = dateInvoice;
       this.idInvoice = idInvoice;
       this.typeInvoice = typeInvoice;
       this.type = type;
       this.invoiceStatus = invoiceStatus;
       this.duedateInvoice = duedateInvoice;
       this.vat = vat;
       this.acceptancedetailses = acceptancedetailses;
       this.payments = payments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idacceptance", unique=true, nullable=false)
    public Integer getIdacceptance() {
        return this.idacceptance;
    }
    
    public void setIdacceptance(Integer idacceptance) {
        this.idacceptance = idacceptance;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="paymentterm_idpaymentterm", nullable=false)
    public Paymentterm getPaymentterm() {
        return this.paymentterm;
    }
    
    public void setPaymentterm(Paymentterm paymentterm) {
        this.paymentterm = paymentterm;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateAcceptance", length=10)
    public Date getDateAcceptance() {
        return this.dateAcceptance;
    }
    
    public void setDateAcceptance(Date dateAcceptance) {
        this.dateAcceptance = dateAcceptance;
    }
    
    @Column(name="numero", length=45)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    
    @Column(name="linkGed", length=450)
    public String getLinkGed() {
        return this.linkGed;
    }
    
    public void setLinkGed(String linkGed) {
        this.linkGed = linkGed;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="dateInvoice", length=10)
    public Date getDateInvoice() {
        return this.dateInvoice;
    }
    
    public void setDateInvoice(Date dateInvoice) {
        this.dateInvoice = dateInvoice;
    }
    
    @Column(name="idInvoice", length=45)
    public String getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(String idInvoice) {
        this.idInvoice = idInvoice;
    }
    
    @Column(name="typeInvoice", length=45)
    public String getTypeInvoice() {
        return this.typeInvoice;
    }
    
    public void setTypeInvoice(String typeInvoice) {
        this.typeInvoice = typeInvoice;
    }
    
    @Column(name="type", length=200)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="invoiceStatus", length=45)
    public String getInvoiceStatus() {
        return this.invoiceStatus;
    }
    
    public void setInvoiceStatus(String invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="duedateInvoice", length=10)
    public Date getDuedateInvoice() {
        return this.duedateInvoice;
    }
    
    public void setDuedateInvoice(Date duedateInvoice) {
        this.duedateInvoice = duedateInvoice;
    }
    
    @Column(name="vat", precision=22, scale=0)
    public Double getVat() {
        return this.vat;
    }
    
    public void setVat(Double vat) {
        this.vat = vat;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="acceptance")
    public Set<Acceptancedetails> getAcceptancedetailses() {
        return this.acceptancedetailses;
    }
    
    public void setAcceptancedetailses(Set<Acceptancedetails> acceptancedetailses) {
        this.acceptancedetailses = acceptancedetailses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="acceptance")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


