package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Budgetpayment generated by hbm2java
 */
@Entity
@Table(name="budgetpayment"
    ,catalog="mypm"
)
public class Budgetpayment  implements java.io.Serializable {


     private Integer idbudgetpayment;
     private Budget budget;
     private String status;
     private String nature;
     private String mode;
     private Double amount;
     private Double percentage;
     private String chequeNb;
     private String chequeDetails;

    public Budgetpayment() {
    }

	
    public Budgetpayment(Budget budget) {
        this.budget = budget;
    }
    public Budgetpayment(Budget budget, String status, String nature, String mode, Double amount, Double percentage, String chequeNb, String chequeDetails) {
       this.budget = budget;
       this.status = status;
       this.nature = nature;
       this.mode = mode;
       this.amount = amount;
       this.percentage = percentage;
       this.chequeNb = chequeNb;
       this.chequeDetails = chequeDetails;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idbudgetpayment", unique=true, nullable=false)
    public Integer getIdbudgetpayment() {
        return this.idbudgetpayment;
    }
    
    public void setIdbudgetpayment(Integer idbudgetpayment) {
        this.idbudgetpayment = idbudgetpayment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="budget_idbudget", nullable=false)
    public Budget getBudget() {
        return this.budget;
    }
    
    public void setBudget(Budget budget) {
        this.budget = budget;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="nature", length=45)
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }
    
    @Column(name="mode", length=45)
    public String getMode() {
        return this.mode;
    }
    
    public void setMode(String mode) {
        this.mode = mode;
    }
    
    @Column(name="amount", precision=22, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    
    @Column(name="percentage", precision=22, scale=0)
    public Double getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(Double percentage) {
        this.percentage = percentage;
    }
    
    @Column(name="chequeNb", length=100)
    public String getChequeNb() {
        return this.chequeNb;
    }
    
    public void setChequeNb(String chequeNb) {
        this.chequeNb = chequeNb;
    }
    
    @Column(name="chequeDetails", length=500)
    public String getChequeDetails() {
        return this.chequeDetails;
    }
    
    public void setChequeDetails(String chequeDetails) {
        this.chequeDetails = chequeDetails;
    }




}


