package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catalog generated by hbm2java
 */
@Entity
@Table(name="catalog"
    ,catalog="mypm"
)
public class Catalog  implements java.io.Serializable {


     private Integer idcatalog;
     private Supplier supplier;
     private String name;
     private String currency;
     private Integer idcontract;
     private Set<Catalogdetail> catalogdetails = new HashSet<Catalogdetail>(0);

    public Catalog() {
    }

    public Catalog(Supplier supplier, String name, String currency, Integer idcontract, Set<Catalogdetail> catalogdetails) {
       this.supplier = supplier;
       this.name = name;
       this.currency = currency;
       this.idcontract = idcontract;
       this.catalogdetails = catalogdetails;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idcatalog", unique=true, nullable=false)
    public Integer getIdcatalog() {
        return this.idcatalog;
    }
    
    public void setIdcatalog(Integer idcatalog) {
        this.idcatalog = idcatalog;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_idsupplier")
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="currency", length=45)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    
    @Column(name="idcontract")
    public Integer getIdcontract() {
        return this.idcontract;
    }
    
    public void setIdcontract(Integer idcontract) {
        this.idcontract = idcontract;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catalog")
    public Set<Catalogdetail> getCatalogdetails() {
        return this.catalogdetails;
    }
    
    public void setCatalogdetails(Set<Catalogdetail> catalogdetails) {
        this.catalogdetails = catalogdetails;
    }




}


