package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contractsupp generated by hbm2java
 */
@Entity
@Table(name="contractsupp"
    ,catalog="mypm"
)
public class Contractsupp  implements java.io.Serializable {


     private Integer idcontractsupp;
     private String reference;
     private String description;
     private String year;
     private Date startDate;
     private Date expiryDate;
     private Double value;
     private String linkGed;
     private String status;
     private int supplierIdsupplier;

    public Contractsupp() {
    }

	
    public Contractsupp(int supplierIdsupplier) {
        this.supplierIdsupplier = supplierIdsupplier;
    }
    public Contractsupp(String reference, String description, String year, Date startDate, Date expiryDate, Double value, String linkGed, String status, int supplierIdsupplier) {
       this.reference = reference;
       this.description = description;
       this.year = year;
       this.startDate = startDate;
       this.expiryDate = expiryDate;
       this.value = value;
       this.linkGed = linkGed;
       this.status = status;
       this.supplierIdsupplier = supplierIdsupplier;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idcontractsupp", unique=true, nullable=false)
    public Integer getIdcontractsupp() {
        return this.idcontractsupp;
    }
    
    public void setIdcontractsupp(Integer idcontractsupp) {
        this.idcontractsupp = idcontractsupp;
    }
    
    @Column(name="reference", length=45)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    
    @Column(name="description", length=450)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="year", length=45)
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="startDate", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="expiryDate", length=10)
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }
    
    @Column(name="value", precision=22, scale=0)
    public Double getValue() {
        return this.value;
    }
    
    public void setValue(Double value) {
        this.value = value;
    }
    
    @Column(name="linkGed", length=500)
    public String getLinkGed() {
        return this.linkGed;
    }
    
    public void setLinkGed(String linkGed) {
        this.linkGed = linkGed;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="supplier_idsupplier", nullable=false)
    public int getSupplierIdsupplier() {
        return this.supplierIdsupplier;
    }
    
    public void setSupplierIdsupplier(int supplierIdsupplier) {
        this.supplierIdsupplier = supplierIdsupplier;
    }




}


