package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="mypm"
)
public class Customer  implements java.io.Serializable {


     private Integer idcustomer;
     private String name;
     private String country;
     private String address;
     private String ri;
     private String vat;
     private String contact;
     private String linkGed;
     private String accountManager;
     private String code;
     private Set<Project> projects = new HashSet<Project>(0);
     private Set<Contract> contracts = new HashSet<Contract>(0);

    public Customer() {
    }

    public Customer(String name, String country, String address, String ri, String vat, String contact, String linkGed, String accountManager, String code, Set<Project> projects, Set<Contract> contracts) {
       this.name = name;
       this.country = country;
       this.address = address;
       this.ri = ri;
       this.vat = vat;
       this.contact = contact;
       this.linkGed = linkGed;
       this.accountManager = accountManager;
       this.code = code;
       this.projects = projects;
       this.contracts = contracts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idcustomer", unique=true, nullable=false)
    public Integer getIdcustomer() {
        return this.idcustomer;
    }
    
    public void setIdcustomer(Integer idcustomer) {
        this.idcustomer = idcustomer;
    }
    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="country", length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="address", length=999)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="ri", length=45)
    public String getRi() {
        return this.ri;
    }
    
    public void setRi(String ri) {
        this.ri = ri;
    }
    
    @Column(name="vat", length=45)
    public String getVat() {
        return this.vat;
    }
    
    public void setVat(String vat) {
        this.vat = vat;
    }
    
    @Column(name="contact", length=999)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    
    @Column(name="linkGed", length=500)
    public String getLinkGed() {
        return this.linkGed;
    }
    
    public void setLinkGed(String linkGed) {
        this.linkGed = linkGed;
    }
    
    @Column(name="accountManager", length=999)
    public String getAccountManager() {
        return this.accountManager;
    }
    
    public void setAccountManager(String accountManager) {
        this.accountManager = accountManager;
    }
    
    @Column(name="code", length=999)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Contract> getContracts() {
        return this.contracts;
    }
    
    public void setContracts(Set<Contract> contracts) {
        this.contracts = contracts;
    }




}


