package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dayoff generated by hbm2java
 */
@Entity
@Table(name="dayoff"
    ,catalog="mypm"
)
public class Dayoff  implements java.io.Serializable {


     private Integer iddayoff;
     private Date date;
     private String type;
     private String description;

    public Dayoff() {
    }

    public Dayoff(Date date, String type, String description) {
       this.date = date;
       this.type = type;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="iddayoff", unique=true, nullable=false)
    public Integer getIddayoff() {
        return this.iddayoff;
    }
    
    public void setIddayoff(Integer iddayoff) {
        this.iddayoff = iddayoff;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


