package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EInsurranceData generated by hbm2java
 */
@Entity
@Table(name="e_insurrance_data"
    ,catalog="mypm"
)
public class EInsurranceData  implements java.io.Serializable {


     private Integer inssuranceId;
     private String resurceId;
     private String matricule;
     private Date date;
     private String type;
     private Date dateSoins;
     private String dossier;
     private String personName;
     private String totalAmount;
     private String status;
     private String statusDescription;

    public EInsurranceData() {
    }

	
    public EInsurranceData(String resurceId) {
        this.resurceId = resurceId;
    }
    public EInsurranceData(String resurceId, String matricule, Date date, String type, Date dateSoins, String dossier, String personName, String totalAmount, String status, String statusDescription) {
       this.resurceId = resurceId;
       this.matricule = matricule;
       this.date = date;
       this.type = type;
       this.dateSoins = dateSoins;
       this.dossier = dossier;
       this.personName = personName;
       this.totalAmount = totalAmount;
       this.status = status;
       this.statusDescription = statusDescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="INSSURANCE_ID", unique=true, nullable=false)
    public Integer getInssuranceId() {
        return this.inssuranceId;
    }
    
    public void setInssuranceId(Integer inssuranceId) {
        this.inssuranceId = inssuranceId;
    }
    
    @Column(name="RESURCE_ID", nullable=false, length=500)
    public String getResurceId() {
        return this.resurceId;
    }
    
    public void setResurceId(String resurceId) {
        this.resurceId = resurceId;
    }
    
    @Column(name="matricule", length=500)
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATE", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    
    @Column(name="TYPE", length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_soins", length=10)
    public Date getDateSoins() {
        return this.dateSoins;
    }
    
    public void setDateSoins(Date dateSoins) {
        this.dateSoins = dateSoins;
    }
    
    @Column(name="dossier", length=500)
    public String getDossier() {
        return this.dossier;
    }
    
    public void setDossier(String dossier) {
        this.dossier = dossier;
    }
    
    @Column(name="PERSON_NAME", length=100)
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }
    
    @Column(name="TOTAL_AMOUNT")
    public String getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }
    
    @Column(name="STATUS", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="STATUS_DESCRIPTION", length=450)
    public String getStatusDescription() {
        return this.statusDescription;
    }
    
    public void setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
    }




}


