package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ELData generated by hbm2java
 */
@Entity
@Table(name="e_l_data"
    ,catalog="mypm"
)
public class ELData  implements java.io.Serializable {


     private Integer leaveId;
     private String resurceId;
     private String date;
     private String leaveType;
     private Date leaveStartDate;
     private Date leaveEndDate;
     private Integer totalDays;
     private String status;
     private String satatusDescription;

    public ELData() {
    }

	
    public ELData(String resurceId) {
        this.resurceId = resurceId;
    }
    public ELData(String resurceId, String date, String leaveType, Date leaveStartDate, Date leaveEndDate, Integer totalDays, String status, String satatusDescription) {
       this.resurceId = resurceId;
       this.date = date;
       this.leaveType = leaveType;
       this.leaveStartDate = leaveStartDate;
       this.leaveEndDate = leaveEndDate;
       this.totalDays = totalDays;
       this.status = status;
       this.satatusDescription = satatusDescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="LEAVE_ID", unique=true, nullable=false)
    public Integer getLeaveId() {
        return this.leaveId;
    }
    
    public void setLeaveId(Integer leaveId) {
        this.leaveId = leaveId;
    }
    
    @Column(name="RESURCE_ID", nullable=false, length=500)
    public String getResurceId() {
        return this.resurceId;
    }
    
    public void setResurceId(String resurceId) {
        this.resurceId = resurceId;
    }
    
    @Column(name="DATE", length=50)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    
    @Column(name="LEAVE_TYPE", length=100)
    public String getLeaveType() {
        return this.leaveType;
    }
    
    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="LEAVE_START_DATE", length=10)
    public Date getLeaveStartDate() {
        return this.leaveStartDate;
    }
    
    public void setLeaveStartDate(Date leaveStartDate) {
        this.leaveStartDate = leaveStartDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="LEAVE_END_DATE", length=10)
    public Date getLeaveEndDate() {
        return this.leaveEndDate;
    }
    
    public void setLeaveEndDate(Date leaveEndDate) {
        this.leaveEndDate = leaveEndDate;
    }
    
    @Column(name="TOTAL_DAYS")
    public Integer getTotalDays() {
        return this.totalDays;
    }
    
    public void setTotalDays(Integer totalDays) {
        this.totalDays = totalDays;
    }
    
    @Column(name="STATUS", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="SATATUS_DESCRIPTION", length=450)
    public String getSatatusDescription() {
        return this.satatusDescription;
    }
    
    public void setSatatusDescription(String satatusDescription) {
        this.satatusDescription = satatusDescription;
    }




}


