package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Po generated by hbm2java
 */
@Entity
@Table(name="po"
    ,catalog="mypm"
)
public class Po  implements java.io.Serializable {


     private Integer idpo;
     private Supplier supplier;
     private Project project;
     private Contract contract;
     private String numero;
     private Date poDate;
     private String description;
     private String linkGed;
     private String status;
     private String currency;
     private Set<Podetails> podetailses = new HashSet<Podetails>(0);
     private Set<Paymentterm> paymentterms = new HashSet<Paymentterm>(0);

    public Po() {
    }

	
    public Po(Project project) {
        this.project = project;
    }
    public Po(Supplier supplier, Project project, Contract contract, String numero, Date poDate, String description, String linkGed, String status, String currency, Set<Podetails> podetailses, Set<Paymentterm> paymentterms) {
       this.supplier = supplier;
       this.project = project;
       this.contract = contract;
       this.numero = numero;
       this.poDate = poDate;
       this.description = description;
       this.linkGed = linkGed;
       this.status = status;
       this.currency = currency;
       this.podetailses = podetailses;
       this.paymentterms = paymentterms;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idpo", unique=true, nullable=false)
    public Integer getIdpo() {
        return this.idpo;
    }
    
    public void setIdpo(Integer idpo) {
        this.idpo = idpo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="supplier_idsupplier")
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_idproject", nullable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contract_idcontract")
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }
    
    @Column(name="numero", length=45)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="poDate", length=10)
    public Date getPoDate() {
        return this.poDate;
    }
    
    public void setPoDate(Date poDate) {
        this.poDate = poDate;
    }
    
    @Column(name="description", length=450)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="linkGed", length=450)
    public String getLinkGed() {
        return this.linkGed;
    }
    
    public void setLinkGed(String linkGed) {
        this.linkGed = linkGed;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="currency", length=45)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="po")
    public Set<Podetails> getPodetailses() {
        return this.podetailses;
    }
    
    public void setPodetailses(Set<Podetails> podetailses) {
        this.podetailses = podetailses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="po")
    public Set<Paymentterm> getPaymentterms() {
        return this.paymentterms;
    }
    
    public void setPaymentterms(Set<Paymentterm> paymentterms) {
        this.paymentterms = paymentterms;
    }




}


