package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Podetails generated by hbm2java
 */
@Entity
@Table(name="podetails"
    ,catalog="mypm"
)
public class Podetails  implements java.io.Serializable {


     private Integer idpoDetails;
     private Po po;
     private String description;
     private Double unit;
     private Double unitPrice;
     private Double totalPrice;
     private String currency;
     private String status;
     private String reference;
     private String unite;
     private Set<Acceptancedetails> acceptancedetailses = new HashSet<Acceptancedetails>(0);

    public Podetails() {
    }

	
    public Podetails(Po po) {
        this.po = po;
    }
    public Podetails(Po po, String description, Double unit, Double unitPrice, Double totalPrice, String currency, String status, String reference, String unite, Set<Acceptancedetails> acceptancedetailses) {
       this.po = po;
       this.description = description;
       this.unit = unit;
       this.unitPrice = unitPrice;
       this.totalPrice = totalPrice;
       this.currency = currency;
       this.status = status;
       this.reference = reference;
       this.unite = unite;
       this.acceptancedetailses = acceptancedetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idpoDetails", unique=true, nullable=false)
    public Integer getIdpoDetails() {
        return this.idpoDetails;
    }
    
    public void setIdpoDetails(Integer idpoDetails) {
        this.idpoDetails = idpoDetails;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="po_idpo", nullable=false)
    public Po getPo() {
        return this.po;
    }
    
    public void setPo(Po po) {
        this.po = po;
    }
    
    @Column(name="description", length=5000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="unit", precision=22, scale=0)
    public Double getUnit() {
        return this.unit;
    }
    
    public void setUnit(Double unit) {
        this.unit = unit;
    }
    
    @Column(name="unitPrice", precision=22, scale=0)
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    
    @Column(name="totalPrice", precision=22, scale=0)
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    
    @Column(name="currency", length=45)
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="reference", length=100)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }
    
    @Column(name="unite", length=45)
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="podetails")
    public Set<Acceptancedetails> getAcceptancedetailses() {
        return this.acceptancedetailses;
    }
    
    public void setAcceptancedetailses(Set<Acceptancedetails> acceptancedetailses) {
        this.acceptancedetailses = acceptancedetailses;
    }




}


