package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name="task"
    ,catalog="mypm"
)
public class Task  implements java.io.Serializable {


     private Integer idtask;
     private Project project;
     private String name;
     private Set<Usertimesheetline> usertimesheetlines = new HashSet<Usertimesheetline>(0);

    public Task() {
    }

	
    public Task(Project project) {
        this.project = project;
    }
    public Task(Project project, String name, Set<Usertimesheetline> usertimesheetlines) {
       this.project = project;
       this.name = name;
       this.usertimesheetlines = usertimesheetlines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idtask", unique=true, nullable=false)
    public Integer getIdtask() {
        return this.idtask;
    }
    
    public void setIdtask(Integer idtask) {
        this.idtask = idtask;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_idproject", nullable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    
    @Column(name="name", length=999)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="task")
    public Set<Usertimesheetline> getUsertimesheetlines() {
        return this.usertimesheetlines;
    }
    
    public void setUsertimesheetlines(Set<Usertimesheetline> usertimesheetlines) {
        this.usertimesheetlines = usertimesheetlines;
    }




}


