package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsertimesheetId generated by hbm2java
 */
@Embeddable
public class UsertimesheetId  implements java.io.Serializable {


     private String usersUsername;
     private int timesheetIdtimesheet;

    public UsertimesheetId() {
    }

    public UsertimesheetId(String usersUsername, int timesheetIdtimesheet) {
       this.usersUsername = usersUsername;
       this.timesheetIdtimesheet = timesheetIdtimesheet;
    }
   

    @Column(name="users_username", nullable=false, length=45)
    public String getUsersUsername() {
        return this.usersUsername;
    }
    
    public void setUsersUsername(String usersUsername) {
        this.usersUsername = usersUsername;
    }

    @Column(name="timesheet_idtimesheet", nullable=false)
    public int getTimesheetIdtimesheet() {
        return this.timesheetIdtimesheet;
    }
    
    public void setTimesheetIdtimesheet(int timesheetIdtimesheet) {
        this.timesheetIdtimesheet = timesheetIdtimesheet;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsertimesheetId) ) return false;
		 UsertimesheetId castOther = ( UsertimesheetId ) other; 
         
		 return ( (this.getUsersUsername()==castOther.getUsersUsername()) || ( this.getUsersUsername()!=null && castOther.getUsersUsername()!=null && this.getUsersUsername().equals(castOther.getUsersUsername()) ) )
 && (this.getTimesheetIdtimesheet()==castOther.getTimesheetIdtimesheet());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsersUsername() == null ? 0 : this.getUsersUsername().hashCode() );
         result = 37 * result + this.getTimesheetIdtimesheet();
         return result;
   }   


}


