package com.com3g.myPm.domaine;
// Generated 12 ao�t 2012 17:58:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsertimesheetlineId generated by hbm2java
 */
@Embeddable
public class UsertimesheetlineId  implements java.io.Serializable {


     private String usersHasTimesheetUsersUsername;
     private int usersHasTimesheetTimesheetIdtimesheet;
     private int taskIdtask;
     private Date day;

    public UsertimesheetlineId() {
    }

    public UsertimesheetlineId(String usersHasTimesheetUsersUsername, int usersHasTimesheetTimesheetIdtimesheet, int taskIdtask, Date day) {
       this.usersHasTimesheetUsersUsername = usersHasTimesheetUsersUsername;
       this.usersHasTimesheetTimesheetIdtimesheet = usersHasTimesheetTimesheetIdtimesheet;
       this.taskIdtask = taskIdtask;
       this.day = day;
    }
   

    @Column(name="users_has_timesheet_users_username", nullable=false, length=45)
    public String getUsersHasTimesheetUsersUsername() {
        return this.usersHasTimesheetUsersUsername;
    }
    
    public void setUsersHasTimesheetUsersUsername(String usersHasTimesheetUsersUsername) {
        this.usersHasTimesheetUsersUsername = usersHasTimesheetUsersUsername;
    }

    @Column(name="users_has_timesheet_timesheet_idtimesheet", nullable=false)
    public int getUsersHasTimesheetTimesheetIdtimesheet() {
        return this.usersHasTimesheetTimesheetIdtimesheet;
    }
    
    public void setUsersHasTimesheetTimesheetIdtimesheet(int usersHasTimesheetTimesheetIdtimesheet) {
        this.usersHasTimesheetTimesheetIdtimesheet = usersHasTimesheetTimesheetIdtimesheet;
    }

    @Column(name="task_idtask", nullable=false)
    public int getTaskIdtask() {
        return this.taskIdtask;
    }
    
    public void setTaskIdtask(int taskIdtask) {
        this.taskIdtask = taskIdtask;
    }

    @Column(name="day", nullable=false, length=10)
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsertimesheetlineId) ) return false;
		 UsertimesheetlineId castOther = ( UsertimesheetlineId ) other; 
         
		 return ( (this.getUsersHasTimesheetUsersUsername()==castOther.getUsersHasTimesheetUsersUsername()) || ( this.getUsersHasTimesheetUsersUsername()!=null && castOther.getUsersHasTimesheetUsersUsername()!=null && this.getUsersHasTimesheetUsersUsername().equals(castOther.getUsersHasTimesheetUsersUsername()) ) )
 && (this.getUsersHasTimesheetTimesheetIdtimesheet()==castOther.getUsersHasTimesheetTimesheetIdtimesheet())
 && (this.getTaskIdtask()==castOther.getTaskIdtask())
 && ( (this.getDay()==castOther.getDay()) || ( this.getDay()!=null && castOther.getDay()!=null && this.getDay().equals(castOther.getDay()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsersHasTimesheetUsersUsername() == null ? 0 : this.getUsersHasTimesheetUsersUsername().hashCode() );
         result = 37 * result + this.getUsersHasTimesheetTimesheetIdtimesheet();
         result = 37 * result + this.getTaskIdtask();
         result = 37 * result + ( getDay() == null ? 0 : this.getDay().hashCode() );
         return result;
   }   


}


